#!/usr/bin/env python3
"""Evidence writer module for TDD artifact generation and cleanup.

This module provides a unified interface for TDD evidence tracking using
the EvidenceManager JSON ledger system, providing single source of truth
for /code and /tdd evidence tracking.
"""

import json
import logging
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Configure logging
logger = logging.getLogger(__name__)

# Import EvidenceManager for unified evidence tracking
import sys

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "code" / "utils"))
try:
    from evidence import EvidenceManager
    EVIDENCE_MANAGER_AVAILABLE = True
except ImportError:
    EVIDENCE_MANAGER_AVAILABLE = False
    logger.warning("EvidenceManager not available - falling back to markdown mode")


def debug_log(message: str) -> None:
    """Log debug message if debug mode is enabled."""
    if os.environ.get("TDD_EVIDENCE_DEBUG"):
        logger.debug(message)


def is_evidence_tracking_enabled() -> bool:
    """Check if evidence tracking is enabled via environment variable.

    Returns:
        True if TDD_EVIDENCE_TRACKING_ENABLED is "true", False otherwise
    """
    return os.environ.get("TDD_EVIDENCE_TRACKING_ENABLED", "false").lower() == "true"


def generate_evidence_artifact(
    task_id: str,
    phase: str,
    evidence: dict[str, Any],
    skill_dir: Path,
    terminal_id: str | None = None
) -> Path | None:
    """Generate evidence artifact using unified JSON ledger system.

    This function uses EvidenceManager to record TDD evidence in a JSON ledger,
    providing single source of truth for /code and /tdd evidence tracking.

    Args:
        task_id: TDD task identifier (e.g., "TASK-001")
        phase: TDD phase (RED, GREEN, REFACTOR, VERIFY)
        evidence: Evidence dictionary containing phase-specific details
        skill_dir: Path to the skill directory (for fallback markdown mode)
        terminal_id: Terminal ID for EvidenceManager isolation

    Returns:
        Path to evidence ledger file, or None if disabled/error
    """
    if not is_evidence_tracking_enabled():
        debug_log("generate_evidence_artifact: Evidence tracking disabled")
        return None

    try:
        # Use EvidenceManager if available (preferred mode)
        if EVIDENCE_MANAGER_AVAILABLE and terminal_id:
            debug_log(f"generate_evidence_artifact: Using EvidenceManager for {task_id} {phase}")

            # Import and initialize EvidenceManager
            manager = EvidenceManager(terminal_id)

            # Use /tdd-specific method that handles generic evidence dict
            manager.record_tdd_evidence(task_id, phase, evidence)

            # Return path to ledger file for reference
            debug_log(f"generate_evidence_artifact: Evidence recorded in {manager.ledger_file}")
            return manager.ledger_file

        # Fallback to markdown generation if EvidenceManager unavailable
        else:
            debug_log(f"generate_evidence_artifact: EvidenceManager unavailable, using markdown fallback for {task_id} {phase}")
            debug_log(f"generate_evidence_artifact: EVIDENCE_MANAGER_AVAILABLE={EVIDENCE_MANAGER_AVAILABLE}, terminal_id={terminal_id}")

            # Create .evidence directory
            evidence_dir = skill_dir / ".evidence"
            evidence_dir.mkdir(parents=True, exist_ok=True)

            # Generate artifact filename with UTC timestamp
            timestamp = evidence.get("timestamp", datetime.now(timezone.utc).isoformat())
            date_str = timestamp.split("T")[0] if timestamp else "unknown"
            time_str = timestamp.split("T")[1].split(":")[0:3] if "T" in timestamp else "0000"
            time_str = "".join(time_str)  # Remove colons
            artifact_name = f"{task_id}_{phase}_{date_str}_{time_str}.md"
            artifact_path = evidence_dir / artifact_name

            # Generate markdown content
            content = f"""# {phase} Evidence - {task_id}

**Timestamp**: {timestamp}
**Phase**: {phase}
**Terminal ID**: {terminal_id or "default"}

## Evidence Details

```json
{json.dumps(evidence, indent=2)}
```

---

This artifact was automatically generated by the TDD evidence tracking system.
Task ID: {task_id}
Phase: {phase}
"""

            # Write artifact
            artifact_path.write_text(content, encoding="utf-8")
            debug_log(f"generate_evidence_artifact: Created artifact at {artifact_path}")

            return artifact_path

    except Exception as e:
        debug_log(f"generate_evidence_artifact: Error generating artifact: {e}")
        return None


def _get_terminal_id() -> str:
    """Get current terminal ID with sanitization (avoids importing hook_base).

    Priority:
    1. CLAUDE_TERMINAL_ID env var (highest)
    2. TERMINAL_ID, TERM_ID, SESSION_TERMINAL env vars
    3. Derive from PID + timestamp (fallback)
    """
    import hashlib
    import re

    _PATTERN = re.compile(r"^[a-zA-Z0-9_-]{1,64}$")
    for env_var in ["CLAUDE_TERMINAL_ID", "TERMINAL_ID", "TERM_ID", "SESSION_TERMINAL"]:
        value = os.environ.get(env_var, "").strip()
        if value and _PATTERN.match(value):
            return value
    try:
        pid = os.getpid()
        timestamp = int(datetime.now().timestamp())
        unique = f"{pid}_{timestamp}".encode()
        return hashlib.sha1(unique).hexdigest()[:12]
    except (OSError, RuntimeError):
        return "unknown"


def cleanup_old_evidence(evidence_dir: Path, max_days: int = 7, terminal_id: str | None = None) -> int:
    """Clean up evidence artifacts older than max_days.

    This function cleans up both JSON ledger files (from EvidenceManager)
    and markdown files (legacy fallback mode). JSON ledger cleanup is scoped
    to the current terminal to prevent cross-terminal deletion.

    Args:
        evidence_dir: Path to .evidence directory (for legacy markdown files)
        max_days: Maximum age in days (default: 7)
        terminal_id: Terminal ID for ledger cleanup scope (default: auto-detect)

    Returns:
        Number of artifacts cleaned up
    """
    cleaned_count = 0

    # Clean up legacy markdown files
    if evidence_dir.exists():
        try:
            cutoff_time = time.time() - (max_days * 24 * 60 * 60)

            for artifact_path in evidence_dir.glob("*.md"):
                if artifact_path.stat().st_mtime < cutoff_time:
                    artifact_path.unlink()
                    cleaned_count += 1
                    debug_log(f"cleanup_old_evidence: Removed old markdown artifact {artifact_path.name}")

        except Exception as e:
            debug_log(f"cleanup_old_evidence: Error during markdown cleanup: {e}")

    # Clean up JSON ledger files from EvidenceManager (terminal-scoped)
    if EVIDENCE_MANAGER_AVAILABLE:
        try:
            tid = terminal_id or _get_terminal_id()
            state_dir = Path(".claude/state")
            if state_dir.exists():
                cutoff_time = time.time() - (max_days * 24 * 60 * 60)
                # Terminal-scoped: only delete ledgers belonging to current terminal
                for ledger_file in state_dir.glob(f"code_evidence_{tid}*"):
                    if ledger_file.stat().st_mtime < cutoff_time:
                        ledger_file.unlink()
                        cleaned_count += 1
                        debug_log(f"cleanup_old_evidence: Removed old ledger {ledger_file.name}")

        except Exception as e:
            debug_log(f"cleanup_old_evidence: Error during ledger cleanup: {e}")

    debug_log(f"cleanup_old_evidence: Cleaned {cleaned_count} artifact(s)")
    return cleaned_count


def cleanup_all_evidence(evidence_dir: Path) -> int:
    """Complete rollback cleanup - remove ALL evidence including directory itself.

    This function performs complete cleanup for rollback scenarios, removing
    the entire .evidence/ directory and all its contents. This ensures zero
    residual state after rollback.

    Args:
        evidence_dir: Path to .evidence directory

    Returns:
        Number of directories removed (0 or 1)
    """
    removed_count = 0

    # Remove entire .evidence/ directory if it exists
    if evidence_dir.exists():
        try:
            shutil.rmtree(evidence_dir)
            removed_count = 1
            debug_log(f"cleanup_all_evidence: Removed complete .evidence/ directory at {evidence_dir}")
        except Exception as e:
            debug_log(f"cleanup_all_evidence: Error removing .evidence/ directory: {e}")

    debug_log(f"cleanup_all_evidence: Removed {removed_count} director(y)(ies)")
    return removed_count
