#!/usr/bin/env python3
"""
Stop agent hook for /refactor skill.
Spawns a verification subagent to check all completion criteria before allowing STOP.
Auto-generated by /av improve /refactor

This is the primary self-verification mechanism for workflow skills.
The agent-type Stop hook validates that ALL phase completion criteria are met
before permitting the skill session to end.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from state_manager_refactor import read_state, PHASES

# Verification checklist for /refactor
COMPLETION_CHECKLIST = [
    ("PREFLIGHT", "migration_detected", "migration shim created and verified OR no migration detected"),
    ("PREFLIGHT", "no_migration", "pure code quality refactor - no path changes"),
    ("DISCOVERY", "findings_exist", "deduplicated.json exists with findings"),
    ("DISCOVERY", "agent_analysis_done", "8-agent analysis completed"),
    ("PLANNING", "plan_created", "refactor_plan.json exists"),
    ("PLANNING", "adversarial_review_passed", "adversarial review output passed"),
    ("RED_PHASE", "characterization_tests_fail", "TDD characterization tests verified failing before changes"),
    ("CHECKPOINT_RED", "git_tag_created", "refactor/red-* git tag exists"),
    ("REFACTOR", "green_phase_complete", "code changes applied"),
    ("LSP_VALIDATE", "no_type_errors", "LSP diagnostics show no errors"),
    ("CHECKPOINT_GREEN", "git_tag_created", "refactor/green-* git tag exists"),
    ("REGRESSION", "all_tests_pass", "full test suite passes with 0 new failures"),
    ("CODE_SIMPLIFICATION", "code_simplifier_run", "code-simplifier applied"),
    ("DELETION_METRIC", "recorded", "deletion metric calculated and positive or justified"),
]

def build_verification_prompt(state: dict) -> str:
    """Build the verification prompt for the Stop agent."""
    phase = state.get("phase", "unknown")
    evidence = state.get("evidence", {})
    artifacts_dir = evidence.get("artifacts_dir", "P:/.claude/.artifacts/{terminal_id}/refactor")

    prompt = f"""You are the /refactor self-verification agent. Verify ALL completion criteria before allowing STOP.

Current phase: {phase}
Skill: /refactor (Multi-File Refactoring Orchestrator)

## Verification Checklist

For each item, check the evidence and report PASS or FAIL:

### PREFLIGHT
- [ ] shim created at old_path (if migration) OR no_migration flag set

### DISCOVERY
- [ ] artifacts exist at: {artifacts_dir}/refactor/deduplicated.json
- [ ] 8-agent analysis output present

### PLANNING
- [ ] plan.json exists at: {artifacts_dir}/refactor/plan.json
- [ ] adversarial_review.json exists and shows passed=true

### RED PHASE
- [ ] Characterization test file exists and FAILS (confirm before-image captured)

### CHECKPOINT_RED
- [ ] Git tag refactor/red-* exists (run: git tag | grep refactor/red)

### LSP_VALIDATE
- [ ] No type errors in LSP diagnostics output

### CHECKPOINT_GREEN
- [ ] Git tag refactor/green-* exists

### REGRESSION
- [ ] Full test suite output shows 0 new failures

### DELETION_METRIC
- [ ] deletion_metric recorded in quality report

## Output Format

Return a JSON object:
{{
  "verification_complete": true/false,
  "phase": "{phase}",
  "checks": [
    {{"name": "...", "status": "PASS|FAIL", "evidence": "file path or output snippet"}}
  ],
  "can_stop": true/false,
  "blocking_gaps": ["list of incomplete items preventing STOP"]
}}

If can_stop=false, list the blocking_gaps. Claude Code will use this to either
allow STOP or return to completing the missing items.
"""
    return prompt

def main():
    input_data = json.loads(sys.stdin.read())

    state = read_state()
    if not state:
        # No active state - skill may have completed or not started
        # Output the verification prompt for the agent
        prompt = """You are the /refactor self-verification agent.
No active state found. Verify whether /refactor work is complete.

Check for:
1. deduplicated.json in artifacts/refactor/
2. plan.json in artifacts/refactor/
3. refactor/green-* git tag
4. regression test output

Return JSON: {{"can_stop": true/false, "checks": [...], "blocking_gaps": [...]}}"""
        print(prompt)
        sys.exit(0)
        return

    verification_prompt = build_verification_prompt(state)
    print(verification_prompt)

    sys.exit(0)

if __name__ == "__main__":
    main()