"""HANDOFF Sync - generates the sentinel-delimited worktree section in HANDOFF.md.

PR 4 of P:/docs/worktree-lifecycle-design.md. Replaces the manual HANDOFF.md
edits with an automated generated block. The worktree status section becomes
sentinel-delimited so:
- Manual edits outside the sentinel are preserved
- The worktree block can be regenerated without diff conflicts
- Drift (the bug that caused the 14h-stale "not yet merged" claim) is impossible

Public API:
- generate_block(worktrees: list[WorktreeState]) -> str
- sync(repo_root, handoff_path, main_branch="main") -> bool (True if updated)
"""
from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


# Sentinel markers. The block lives between these lines in HANDOFF.md.
# Manual edits outside the sentinels are preserved; the block itself is regenerated.
SENTINEL_BEGIN = "<!-- BEGIN worktree-status (auto-generated; do not edit) -->"
SENTINEL_END = "<!-- END worktree-status -->"


@dataclass
class WorktreeState:
    """Snapshot of a worktree for inclusion in HANDOFF.md."""
    path: str
    branch: str
    behind_main: Optional[int]  # None if not computable (e.g., worktree missing)
    status: str  # "active" | "missing" | "registered" | "error"
    extra: str = ""  # For human-readable notes (e.g., backup-tag preserved)


def collect_worktree_states(repo_root: Path, main_branch: str = "main") -> list[WorktreeState]:
    """Collect current worktree states from `git worktree list --porcelain`."""
    r = subprocess.run(
        ["git", "-C", str(repo_root), "worktree", "list", "--porcelain"],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        return []

    states: list[WorktreeState] = []
    current: dict = {}
    for line in r.stdout.splitlines():
        if line.startswith("worktree "):
            if current.get("path"):
                states.append(_finalize(current, repo_root, main_branch))
            current = {"path": line[len("worktree "):].strip()}
        elif line.startswith("HEAD "):
            current["head"] = line[len("HEAD "):].strip()
        elif line.startswith("branch "):
            current["branch"] = line[len("branch "):].strip().replace("refs/heads/", "")
        elif line.strip() == "detached":
            current["branch"] = "(detached)"
    if current.get("path"):
        states.append(_finalize(current, repo_root, main_branch))
    return states


def _finalize(raw: dict, repo_root: Path, main_branch: str) -> WorktreeState:
    """Convert a parsed porcelain entry to WorktreeState."""
    path = raw.get("path", "?")
    branch = raw.get("branch", "?")
    # Compute behind-main
    behind = None
    try:
        r = subprocess.run(
            ["git", "-C", str(repo_root), "rev-list", "--count",
             f"{branch}..{main_branch}"],
            capture_output=True, text=True,
        )
        if r.returncode == 0 and r.stdout.strip().isdigit():
            behind = int(r.stdout.strip())
    except Exception:
        pass
    return WorktreeState(
        path=path,
        branch=branch,
        behind_main=behind,
        status="active",
    )


def generate_block(states: list[WorktreeState], main_branch: str = "main") -> str:
    """Generate the sentinel-delimited HANDOFF.md block as a string.

    No timestamp in the output (would break change-detection on every call).
    If you need to know when the block was last regenerated, use file mtime
    or `git log -p` on the HANDOFF.md file.
    """
    lines: list[str] = []
    lines.append(SENTINEL_BEGIN)
    lines.append(f"All worktrees relative to `{main_branch}`. Generated by `handoff_sync.sync`.")
    lines.append("")
    if not states:
        lines.append("_(no worktrees registered)_")
    else:
        lines.append("| Path | Branch | Behind " + main_branch + " |")
        lines.append("|------|--------|----------------:|")
        for s in states:
            behind_str = str(s.behind_main) if s.behind_main is not None else "?"
            extra = f" — {s.extra}" if s.extra else ""
            lines.append(f"| `{s.path}` | `{s.branch}` | {behind_str} |{extra}")
    lines.append("")
    lines.append(SENTINEL_END)
    return "\n".join(lines)


def sync(
    repo_root: Path,
    handoff_path: Path,
    *,
    main_branch: str = "main",
) -> bool:
    """Regenerate the sentinel block in HANDOFF.md. Returns True if updated.

    Preserves all content outside the sentinel block (including any
    section heading the caller added). Inserts the sentinel block if
    not present. Does NOT add a heading — that's the caller's choice
    (we don't want sync() to add duplication on subsequent calls).
    """
    repo_root = Path(repo_root)
    handoff_path = Path(handoff_path)

    states = collect_worktree_states(repo_root, main_branch=main_branch)
    new_block = generate_block(states, main_branch=main_branch)

    if handoff_path.exists():
        content = handoff_path.read_text(encoding="utf-8")
    else:
        content = ""

    # Pattern: from sentinel_begin to sentinel_end (multiline, DOTALL)
    pattern = re.compile(
        re.escape(SENTINEL_BEGIN) + r".*?" + re.escape(SENTINEL_END),
        re.DOTALL,
    )

    if pattern.search(content):
        new_content = pattern.sub(new_block, content, count=1)
    else:
        # No existing block — append at end
        if content and not content.endswith("\n"):
            content += "\n"
        if content:
            content += "\n"
        new_content = content + new_block + "\n"

    if new_content == content:
        return False  # No change

    handoff_path.parent.mkdir(parents=True, exist_ok=True)
    # Atomic write: write to temp + rename
    tmp = handoff_path.with_suffix(handoff_path.suffix + ".tmp")
    tmp.write_text(new_content, encoding="utf-8")
    tmp.replace(handoff_path)
    return True