import json
out = "C:/Users/brsth/.claude/plans/reviews/gto-finding-lifecycle-refactor/state-machine.json"
findings = {"findings": []}
d1 = 'The plan State model claims a finding is stale (downgrade to low severity, tag stale) when age_hours exceeds 24h. This is FALSE for the carryover path. The 24h downgrade in hook_health.py only fires at EMISSION time when the transcript is first scanned (_age_hours from the transcript entry timestamp). Once persisted to carryover.json, a HOOK finding age is never recomputed: load_carryover_open_only (carryover.py:110-112) loads as-is, apply_carryover_enrichment (carryover.py:115-147) only escalates severity by _carry_count -- no age/TTL branch. Finding has no created_at or age_hours field; metadata._first_seen exists but nothing reads it for TTL. Net effect: a HOOK-001 emitted at 23h59m stays at original (medium/high) severity through every carryover load forever, unless its hook errors AGAIN in a fresh transcript scan (re-emission), restarting the cycle. Plan test matrix asserts test_stale_finding_ages_out_at_ttl but no code path implements this for carryover. Core freshness contract violation the plan claims to preserve.'
f1 = 'Add a TTL downgrade pass in apply_carryover_enrichment: for source_type=carryover, read metadata._first_seen, compute age, if > 24h downgrade severity to low and tag stale (mirror hook_health.py:143-148). Plan State model must state TTL is enforced at LOAD time on carryover, not only at emission.'
d2 = 'D1 claims a finding resolves iff (a) file in edited set, (b) already status=resolved, or (c) strategy returns non-None. Presented as exhaustive but is not. Three gaps: (1) FindingSourceType includes user (models.py:10) and FindingStatus includes deferred/mapped/rejected (models.py:8) -- legitimate terminal states, but D1 logic only sets status=resolved. A user-deferred finding has no transition path; resolve_findings only checks status=resolved (signal 2) and otherwise may re-resolve a user-deferred finding back to resolved via file-edit match, clobbering user state. (2) NO validation prevents resolved-to-open or rejected-to-resolved. _try_resolve short-circuits on status=resolved but NOT on rejected or deferred -- a deferred finding kept in carryover (save_carryover skips only rejected at line 91) can be re-resolved and re-opened. (3) grep confirms nothing ever sets status=stale (enum value dead), so plan stale state is fictional as a status -- only a severity+tag, contradicting State model implication that stale is a lifecycle state.'
f2 = 'Make D1 explicit about valid vs terminal transitions. Add guard in _try_resolve: if f.status in {rejected,deferred,mapped} return None. Either remove stale from FindingStatus or actually set status=stale at TTL expiry. Document that user source_type findings resolve only via explicit user action.'
d3 = 'Plan State model claims GTO runs single-threaded per invocation (D1 Concurrency) so no locking needed. True WITHIN one process but FALSE across processes. Artifacts dir shared per terminal_id; two GTO invocations can run concurrently against same terminal_id (hook-triggered racing manual, or two terminals sharing a terminal_id). Sequence: Process A loads carryover.json (open [F1,F2]). Process B loads same. A resolves F1, saves [F1-resolved, F2]. B resolves F2, saves [F1, F2-resolved] -- OVERWRITING A, resurrecting F1 as open. atomic_write_json (util.py:21) only guarantees filesystem-level atomicity (os.replace); does NOT prevent interleaved read-modify-write across processes. Plan mentions no locking, versioning, or last-writer-wins. Identity model one-finding-lifecycle-state-per-terminal claim violated under concurrency -- no per-terminal lock.'
f3 = '(a) file lock (portalocker/fcntl on sibling .lock file) held for load-resolve-save window, OR (b) document last-writer-wins and accept the race (cheapest), OR (c) write-version field and reject saves when on-disk version advanced (optimistic). Minimum: comment that RMW window is unlocked.'
d4 = 'carryover_findings snapshot at line 790 taken BEFORE three downstream mutations: (1) findings_reviewer rejection at 805-806 filters all_findings but NOT carryover_findings -- rejected finding vanishes from display but persists in carryover as open/resolved; (2) Phase 4.7.5 staleness re-check at 912-916 sets status=resolved on workflow_hygiene findings in all_findings and filters them at 916 -- but carryover_findings (snapshotted at 790) still holds them as OPEN. save_carryover at 980 persists them as OPEN though resolved in-memory. Result: finding resolved by staleness re-check in run N resurrected as open in run N+1 carryover. Plan supersede-drop double-drop question answered NO -- but inverse bug: finding in BOTH display-as-resolved AND carryover-as-open simultaneously.'
f4 = 'Move carryover_findings snapshot (line 790) to AFTER all status mutations -- immediately before save_carryover at 980. Ensures persisted state matches final in-memory state. Add test asserting carryover.json status matches display status post-run for a finding touched by reviewer and staleness re-check.'
d5 = 'Plan State model asserts carryover identity is the id alone -- no compound key. But actual dedupe pass over merged findings+carryover (orchestrator.py:778) uses key = f.domain|f.title|f.file (dedupe.py:14). Two inconsistency modes: (1) apply_carryover_enrichment mutates title to RECURRING (Nx): orig (carryover.py:135) -- same finding ID now has different dedupe key than its current-run re-emission (un-prefixed title). If supersede-drop missed it (ID changed), dedupe would NOT catch it because titles diverged. (2) A finding whose title was edited by normalizer (orchestrator.py:811-813, replaces by id) dedupe-collides with a different-ID finding sharing domain+title+file. Plan contract findings never merged by content is only true at supersede-drop -- dedupe downstream violates it.'
f5 = '(a) make dedupe_findings key on f.id (align with plan stated contract), OR (b) update plan State model to acknowledge compound-key dedupe and document that title mutation can cause same-ID findings to bypass dedupe. Option (a) safer given plan invariant.'
d6 = 'Plan State model describes detector-emitted then carried-forward (open) then resolved (dropped) OR stale (downgraded at 24h TTL) as if stale is terminal alongside resolved. But code never sets status=stale. hook_health 24h path (only TTL in system) sets severity=low and prepends (stale, ~Nh old) to title -- status stays open. Means: (a) stale finding still open, still carries forward in carryover.json; (b) load_carryover_open_only loads it; (c) no way to distinguish stale-downgraded from natively-low by status. Plan claim stale findings downgraded at 24h TTL implies a state transition that does not exist. FindingStatus enum value stale is dead code. resolved OR stale branch is misleading -- no stale branch, only severity change within open.'
f6 = '(a) remove stale from FindingStatus (not a status, a severity+tag), update plan to describe stale as severity modifier within open; OR (b) actually implement status=stale at TTL expiry and add load-time TTL check (see SM-001). Option (a) smaller diff, matches reality.'
d7 = 'Signal 2 in _try_resolve (resolve.py:38-40) returns already-resolved finding as-is without re-checking signals 1 or 3. If finding resolved in run N (status=resolved, persisted) and in run N+1 the triggering file is edited again, finding evidence NOT updated. Plan D1 lists three signals as flat OR, but code short-circuits on signal 2 before 1/3, so resolved finding never re-validates conditions still hold. If resolution was transient (DOC-001 resolved because README.md existed at run N, deleted before N+1), finding stays resolved forever -- _detector_recheck would return None but never reached. State-staleness: resolved status sticky even when condition regresses.'
f7 = 'For carryover-sourced resolved findings, re-run signal 3 (detector re-check) to confirm condition holds; if not, transition back to open with evidence resolution regressed. Behavior change -- confirm whether resolved should be sticky or re-validating. Minimum: document sticky-by-design in D1.'
d8 = 'load_carryover_open_only (carryover.py:110-112) filters to status=open at load. Finding resolved in run N NOT in loaded carryover. When run N+1 does NOT re-emit same ID, resolved finding absent from all_findings -- absent from carryover_findings (snapshot 790) -- save_carryover at 980 DROPS it. Result: suppression history lost after one run. If run N+2 re-emits same ID (README deleted again, DOC-001 re-fires), no resolved record to suppress and no _carry_count continuity (metadata reset). Plan comment at orchestrator.py:760 (resolved findings stay suppressed) only true for ONE run; resolved record evaporates next run. Plan test test_stale_finding_ages_out_at_ttl cannot work -- no persistent resolved record to age out.'
f8 = 'In save_carryover, merge resolved findings from PRIOR carryover.json into new carryover before writing, so resolved records persist across runs until pruned by prune_carryover (keeps up to max_resolved=50). Add load_carryover_all (not open-only) at start, pass resolved set through to save_carryover to merge.'
