import json
out = "C:/Users/brsth/.claude/plans/reviews/gto-finding-lifecycle-refactor/state-machine.json"
findings = {"findings": []}
d1 = 'The plan State model claims a finding is stale (downgrade to low severity, tag stale) when age_hours exceeds 24h. This is FALSE for the carryover path. The 24h downgrade in hook_health.py only fires at EMISSION time when the transcript is first scanned (_age_hours from the transcript entry timestamp). Once persisted to carryover.json, a HOOK finding age is never recomputed: load_carryover_open_only (carryover.py:110-112) loads as-is, apply_carryover_enrichment (carryover.py:115-147) only escalates severity by _carry_count -- no age/TTL branch. Finding has no created_at or age_hours field; metadata._first_seen exists but nothing reads it for TTL. Net effect: a HOOK-001 emitted at 23h59m stays at original (medium/high) severity through every carryover load forever, unless its hook errors AGAIN in a fresh transcript scan (re-emission), restarting the cycle. Plan test matrix asserts test_stale_finding_ages_out_at_ttl but no code path implements this for carryover. Core freshness contract violation the plan claims to preserve.'
f1 = 'Add a TTL downgrade pass in apply_carryover_enrichment: for source_type=carryover, read metadata._first_seen, compute age, if > 24h downgrade severity to low and tag stale (mirror hook_health.py:143-148). Plan State model must state TTL is enforced at LOAD time on carryover, not only at emission.'
d2 = 'D1 claims a finding resolves iff (a) file in edited set, (b) already status=resolved, or (c) strategy returns non-None. Presented as exhaustive but is not. Three gaps: (1) FindingSourceType includes user (models.py:10) and FindingStatus includes deferred/mapped/rejected (models.py:8) -- legitimate terminal states, but D1 logic only sets status=resolved. A user-deferred finding has no transition path; resolve_findings only checks status=resolved (signal 2) and otherwise may re-resolve a user-deferred finding back to resolved via file-edit match, clobbering user state. (2) NO validation prevents resolved-to-open or rejected-to-resolved. _try_resolve short-circuits on status=resolved but NOT on rejected or deferred -- a deferred finding kept in carryover (save_carryover skips only rejected at line 91) can be re-resolved and re-opened. (3) grep confirms nothing ever sets status=stale (enum value dead), so plan stale state is fictional as a status -- only a severity+tag, contradicting State model implication that stale is a lifecycle state.'
f2 = 'Make D1 explicit about valid vs terminal transitions. Add guard in _try_resolve: if f.status in {rejected,deferred,mapped} return None. Either remove stale from FindingStatus or actually set status=stale at TTL expiry. Document that user source_type findings resolve only via explicit user action.'
d3 = 'Plan State model claims GTO runs single-threaded per invocation (D1 Concurrency) so no locking needed. True WITHIN one process but FALSE across processes. Artifacts dir shared per terminal_id; two GTO invocations can run concurrently against same terminal_id (hook-triggered racing manual, or two terminals sharing a terminal_id). Sequence: Process A loads carryover.json (open [F1,F2]). Process B loads same. A resolves F1, saves [F1-resolved, F2]. B resolves F2, saves [F1, F2-resolved] -- OVERWRITING A, resurrecting F1 as open. atomic_write_json (util.py:21) only guarantees filesystem-level atomicity (os.replace); does NOT prevent interleaved read-modify-write across processes. Plan mentions no locking, versioning, or last-writer-wins. Identity model one-finding-lifecycle-state-per-terminal claim violated under concurrency -- no per-terminal lock.'
f3 = '(a) file lock (portalocker/fcntl on sibling .lock file) held for load-resolve-save window, OR (b) document last-writer-wins and accept the race (cheapest), OR (c) write-version field and reject saves when on-disk version advanced (optimistic). Minimum: comment that RMW window is unlocked.'
